name: Build and Sign Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Собираем чистый релизный APK без подписи
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Расшифровываем наш секретный ключ безопасности из настроек GitHub
      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app-release-key.jks

      # Официально подписываем APK с помощью встроенного в Android SDK утилиты apksigner
      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/29.0.3/apksigner sign --ks app-release-key.jks --ks-pass pass:12345678 --key-pass pass:12345678 --out Application-signed.apk Application/build/outputs/apk/release/Application-release-unsigned.apk

      # Выкладываем готовый подписанный файл, который встанет на телефон без предупреждений
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: google-hce-card-signed
          path: Application-signed.apk
